---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rivopelu/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R pdf $DEPLOYPATH
    - /bin/cp -R halaman2 $DEPLOYPATH